# Configure and optimize redis server

- name: Increase the value of somaxconn in order to avoid slow clients connections issues
  sysctl:
    name: net.core.somaxconn
    value: "1024"
    state: present

- name: Increase the value of overcommit memory
  sysctl:
    name: vm.overcommit_memory
    value: "1"
    state: present

- name: Disable Linux Kernel support for Transport Huge Pages (THP)
  copy:
    src: disable_thp.service
    dest: /etc/systemd/system/disable_thp.service
    owner: root
    group: root
    mode: 0644
  register: service

- name: Enable + Start service
  systemd:
    name: disable_thp
    daemon_reload: yes
    enabled: yes
    state: started
  when: service is changed

- name: Remove default redis conf
  file:
    path: /etc/redis/redis.conf
    state: absent

- name: Copy openvas redis config
  copy:
    remote_src: yes
    src: /opt/gvm/src/openvas/config/redis-openvas.conf
    dest: /etc/redis/redis-openvas.conf
    owner: redis
    group: redis
    mode: 0640
  register: redis_conf

- name: Configure redis socket
  copy:
    src: openvas.conf
    dest: /opt/gvm/etc/openvas/openvas.conf

- name: Start and enable openvas redis
  systemd:
    name: redis-server@openvas
    state: started
    enabled: yes

- name: Restart openvas redis (in case of config change)
  systemd:
    name: redis-server@openvas
    state: restarted
  when: redis_conf is changed

