- name: Add portnames update script
  copy:
    src: gvm-portnames-update.in
    dest: /opt/gvm/src/gvmd/tools/gvm-portnames-update.in
    owner: gvm
    group: gvm

- name: build and install GVM
  shell: |
    export PKG_CONFIG_PATH=/opt/gvm/lib/pkgconfig:$PKG_CONFIG_PATH
    mkdir build
    cd build/
    cmake -DCMAKE_INSTALL_PREFIX=/opt/gvm ..
    make -j2
    make doc
    make install
  args:
    executable: bash
    chdir: /opt/gvm/src/gvmd/
    creates: /opt/gvm/bin/gvm-manage-certs
  become: yes
  become_user: gvm
  register: build_gvm

- name: Set up Postgres
  shell: |
    createuser -DRS gvm
    createdb -O gvm gvmd
    echo 'create role dba with superuser noinherit; grant dba to gvm; create extension "uuid-ossp";' | psql gvmd
  args:
    executable: bash
  become: yes
  become_user: postgres

- name: fix certs
  command: gvm-manage-certs -a
  become: yes
  become_user: gvm

- name: update certdata feed
  command: greenbone-certdata-sync
  become: yes
  become_user: gvm

- name: update scapdata feed
  command: greenbone-scapdata-sync
  become: yes
  become_user: gvm

- name: download IANA port numbers
  get_url:
    url: https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xml
    dest: /tmp/service-names-port-numbers.xml

- name: update IANA service names
  command: gvm-portnames-update /tmp/service-names-port-numbers.xml
  become: yes
  become_user: gvm

- name: build and install GSA
  shell: |
    export PKG_CONFIG_PATH=/opt/gvm/lib/pkgconfig:$PKG_CONFIG_PATH
    mkdir build
    cd build/
    cmake -DCMAKE_INSTALL_PREFIX=/opt/gvm ..
    make -j2
    make doc
    make install
    touch /opt/gvm/var/log/gvm/gsad.log
  args:
    executable: bash
    chdir: /opt/gvm/src/gsa/
    creates: /opt/gvm/sbin/gsad
  become: yes
  become_user: gvm
  register: build_gsa

- name: build and install OSPd
  shell: |
    export PKG_CONFIG_PATH=/opt/gvm/lib/pkgconfig:$PKG_CONFIG_PATH
    virtualenv --python python3.7  /opt/gvm/bin/ospd-scanner/
    source /opt/gvm/bin/ospd-scanner/bin/activate
    cd ospd
    pip3 install .
    cd ../ospd-openvas
    pip3 install .
  args:
    executable: bash
    chdir: /opt/gvm/src/
    creates: /opt/gvm/bin/ospd-scanner/
  become: yes
  become_user: gvm