- include: apt.yml

- include: build.yml

- include: redis.yml


#- name: create redis configuration
#  copy:
#    -


#
#- name: Create IDE build dir
#  file:
#    path: "{{ theia_ide_install_dir }}"
#    state: directory
#
#- name: Copy IDE configuration to IDE build dir
#  copy:
#    src: package.json
#    dest: "{{ theia_ide_install_dir }}/package.json"
#    mode: 0644
#
#- name: build ide
#  shell: |
#        source {{ nvm_install_dir }}/nvm.sh
#        yarn
#        yarn theia build
#  args:
#    chdir: "{{ theia_ide_install_dir }}"
#    executable: bash
#
#- name: Generate IDE start skript to /usr/local/bin
#  template:
#    src: theia-ide.sh.j2
#    dest: "{{ theia_ide_install_dir }}/theia-ide.sh"
#    mode: 0755
#
#- name: Generate systemd service
#  template:
#    src: theia-ide.service.j2
#    dest: /etc/systemd/system/theia-ide.service
#    mode: 0644
#
#- name: Enable and Start service
#  systemd:
#    name: theia-ide.service
#    enabled: true
#    state: started