- include: openvas_dependencies.yml
  tags:
    - dependencies

- include: openvas_build.yml
  tags:
    - build

- include: redis.yml
  tags:
    - redis

- include: openvas_setup.yml
  tags:
    - setup

- include: openvas_user_management.yml
  tags:
    - user_management

- include: caddy.yml
  tags:
    - caddy