- include: 10-openvas_dependencies.yml
  tags:
    - dependencies

- include: 15-openvas_prep.yml
  tags:
    - prep

- include: 20-openvas_build_1.yml
  tags:
    - build_1

- include: 30-redis.yml
  tags:
    - redis

- include: 32-openvas_setup_1.yml
  tags:
    - setup_1

- include: 35-openvas_build_2.yml
  tags:
    - build_2

- include: 40-openvas_setup_2.yml
  tags:
    - setup_2

- include: 50-openvas_user_management.yml
  tags:
    - user_management

- include: 60-caddy.yml
  tags:
    - caddy