- name: Install yarn (using nodejs)
  shell: |
    npm install -g yarn
  args:
    executable: bash
    creates: /usr/bin/yarn

- name: build and install GVM libaries
  shell: |
    cd /tmp/
    git clone https://github.com/greenbone/gvm-libs.git
    cd gvm-libs
    git fetch && git fetch --tags
    git checkout v10.0.1
    mkdir build
    cd build
    cmake ..
    make
    make install
  args:
    executable: bash
    creates: /usr/local/lib/libgvm_base.so
  register: build_gvmlibs

- name: build and install OpenVAS SMB
  shell: |
    cd /tmp/
    git clone https://github.com/greenbone/openvas-smb.git
    cd openvas-smb
    git fetch && git fetch --tags
    git checkout v1.0.5
    mkdir build
    cd build
    cmake ..
    make
    make install
  args:
    executable: bash
    creates: /usr/local/bin/winexe
  register: build_smb

- name: build and install OpenVAS Scanner
  shell: |
    cd /tmp/
    git clone https://github.com/greenbone/openvas.git
    cd openvas
    git fetch && git fetch --tags
    git checkout v6.0.1
    mkdir build
    cd build
    cmake ..
    make
    make install
  args:
    executable: bash
    creates: /usr/local/bin/openvas-nasl
  register: build_openvas

- name: build and install OSPd
  shell: |
    cd /tmp/
    git clone https://github.com/greenbone/ospd.git
    cd ospd
    git fetch && git fetch --tags
    git checkout v1.3.2
    python3 setup.py install && touch /usr/local/lib/ospd.installed
  args:
    executable: bash
    creates: /usr/local/lib/ospd.installed


- name: build and install GVM
  shell: |
    cd /tmp/
    git clone https://github.com/greenbone/gvmd.git
    cd gvmd
    git fetch && git fetch --tags
    git checkout v8.0.1
    mkdir build
    cd build
    cmake ..
    make
    make install
  args:
    executable: bash
    creates: /usr/local/bin/gvm-manage-certs
  register: build_gvm

- name: build and install GSA
  shell: |
    cd /tmp/
    git clone https://github.com/greenbone/gsa.git
    cd gsa
    git fetch && git fetch --tags
    git checkout v8.0.1
    mkdir build
    cd build
    cmake ..
    make
    make install
  args:
    executable: bash
    creates: /usr/local/sbin/gsad
  register: build_gsa

- name: ldconfig
  shell: ldconfig
  args:
      executable: bash
  when: build_gvmlibs is changed and build_smb and build_openvas and build_gvm is changed and build_gsa is changed